### ISSUE TITLE
Change expiration time for an access token

### ISSUE THREAD

**Issue by 3cees** [julien731/WP-Google-Authenticator#16]
Hi,

is there any way, to change the expiration time of an access token?

Many Thanks in adcance,
Lars

**Comment by julien731** [comment]
You mean the one time password? ( just wording but I need to make sure we're talking about the same thing ;) )

**Comment by 3cees** [comment]
Yep.

**Comment by julien731** [comment]
That is some late reply...

There is no way to change it, simply because TOTP apps (like Google Authenticator) use a 30 secs lifespan for the code.
